version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306"
    env_file:
      - .env.production
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379"
    env_file:
      - .env.production

  web:
    build: .
    links:
      - mysql
      - redis
    command: bin/rails server -p 3000 -e production
    ports:
      - "3030:3000"
    volumes:
      - .:/cover_images
      - ./docker/images:/cover_images/public/system:shared
    env_file:
      - .env.production

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - mysql
      - redis
    volumes:
      - .:/cover_images
    env_file:
      - .env.production

