version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "13306:3306"
    env_file:
      - .env.production

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env.production

  web:
    build: .
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - sidekiq
    command: bin/rails server -p 3000 -b 0.0.0.0 -e production
    ports:
      - "3000:3000"
    volumes:
      - .:/cover_images
      - image-data:/cover_images/public/system
    env_file:
      - .env.production

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/cover_images
      - image-data:/cover_images/public/system
    env_file:
      - .env.production

volumes:
  image_data:
# http://netshare.containx.io/docs/nfs
#   driver: nfs
#   driver_opts:
#     share: some.nfs.host:/path/to/share
