# development will create a and use a 'dev' user
# capistrano will load this file from {deploy_path}/shared/config/authorized_users.yml
# Don't commit changes here
#
# Example
# -------
- mst3k
- test
